# Generated by Django 3.0.6 on 2020-06-14 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_customer_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'date_created'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
