# Generated by Django 3.0.6 on 2020-07-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200716_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost_per_order',
            field=models.FloatField(null=True),
        ),
    ]
