# Generated by Django 3.0.6 on 2020-07-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_total_cost_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost_per_order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
