# requests/api.http



# Send Request

POST http://localhost:8000/api/auth/register

Content-type : application/json



{
    "email": "kirk@gmail.com",
    "password": "dccomics",
    "title": "Mr", 
    "first_name":"James", 
    "middle_name":"T",
    "last_name": "Kirk", 
    "phone": "0788789898", 
    "country": "GB", 
    "birth_year": "2231",
    "gender": "Male",



}